### ISSUE TITLE
Giving error on increasing number of layers? 

### ISSUE THREAD

**Issue by mahi19** [ugnelis/tensorflow-rnn-ctc#15]
`Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _cal
l_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit
__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 100 an
d 63 for 'rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/lstm_cell/MatMul_1' (op: 'MatMul') with input sha
pes: [?,100], [63,200].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 244, in <module>
    tf.app.run()
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 111, in main
    outputs, _ = tf.nn.dynamic_rnn(stack, inputs_placeholder, sequence_length_placeholder, dtype=tf.fl
oat32)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 614, in dynamic_rnn
    dtype=dtype)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 777, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2816, in while_
loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2640, in BuildL
oop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2590, in _Build
Loop
    body_result = body(*packed_vars_for_body)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 760, in _time_step
    skip_conditionals=True)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 236, in _rnn_step
    new_output, new_state = call_cell()
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 748, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "C:\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 1066, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "C:\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 611, in call
    lstm_matrix = self._linear1([inputs, m_prev])
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 1189, in __call__
    res = math_ops.matmul(array_ops.concat(args, 1), self._weights)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1891, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2436, in _mat_mul
    name=name)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _ap
ply_op_helper
    op_def=op_def)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_fo
r_outputs
    shapes = shape_func(op)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_req
uiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call
_cpp_shape_fn
    require_shape_fn)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _cal
l_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 100 and 63 for 'rnn/while/rnn/multi_rnn_cell/cell_0/cell
_0/lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [?,100], [63,200].`

**Comment by ugnelis** [comment]
@mahi19 thank you for reporting issue. I'll try to check/fix this or another week.

**Comment by ugnelis** [comment]
Pull Request #16 solves your problem.
